### ISSUE TITLE
SQLMI deployment took 4 hours to complete the deployment

### ISSUE THREAD

**Issue by sumitmalik51** [microsoft/MCW-Building-the-business-migration-case-with-Windows-Server-and-SQL-Server#4]
Hi Team,

The SQLMI took 4 hours for me to complete the deployment, I think it would be great if we can do it in the BHOL lab.

**Comment by DawnmarieDesJardins** [comment]
@sumitmalik51 
Hi Sumit.  Is it possible for you to try deployment once more and let us know how long it took?  If we can determine if the 4 hours was a fluke vs. what will be standard, we can make a better decision.

**Comment by sumitmalik51** [comment]
Hi @DawnmarieDesJardins , we have checked on the deployment again and it took around 3.5 hrs to complete the deployment.

**Comment by crpietschmann** [comment]
> Hi @DawnmarieDesJardins , we have checked on the deployment again and it took around 3.5 hrs to complete the deployment.

@sumitmalik51  What Azure region are you using? I did a few tests in North Central US as shown in the lab and it's been about 1 hour to provision SQL MI.

**Comment by DawnmarieDesJardins** [comment]
@sumitmalik51 - Hi Sumit.  Can you let us know what region you used?  Is it possible that's why deployment is taking so long?  Our tests are showing around an hour.  If selecting another region shortens it up, we can update the lab to use a particular region.

**Comment by sumitmalik51** [comment]
Hi @crpietschmann , @DawnmarieDesJardins, We have used Central US for the deployment.. 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/45102602/201985661-ffb05783-2c18-46d2-a8de-bad29d33f2a6.png)

**Comment by jeongaelee** [comment]
I had same issue when running workshops twice. Only 1 participant among 80+ people in 2 different workshop was able to complete SQL MI deployment during 5 hours of workshop schedule. Azure regions that were used are East US, South East Asia, Korea Central.

It is also mentioned in Microsoft official document.

https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/management-operations-overview?view=azuresql

![image](https://user-images.githubusercontent.com/6634976/202329394-692329a6-9692-44e2-a836-ea01a8437497.png)

**Comment by DawnmarieDesJardins** [comment]
@jeongaelee @sumitmalik51 
Thank you both for the additional information.  We are working on the request and plan to update the Before the HOL and Hands-on lab documents shortly.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #6
