### ISSUE TITLE
[Before HOL] tailspin-spoke-vnet VNet peering issue

### ISSUE THREAD

**Issue by jeongaelee** [microsoft/MCW-Building-the-business-migration-case-with-Windows-Server-and-SQL-Server#5]
Before HOL script creates peering between tailspin-hub-vnet and tailspin-spoke-vnet, but has below issue to connect. I fixed the issue by deleting and re-creating the peering between hub and spoke VNet.

![image](https://user-images.githubusercontent.com/6634976/202338066-1fbf2dbd-3ce0-4eb2-a7a1-709a1bcf1c8c.png)

**Comment by DawnmarieDesJardins** [comment]
@jeongaelee 
Thank you for letting us know this.  We're working on this, and the other issue together and will have updates for you soon.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #6
