### ISSUE TITLE
Missing Resource and Parameters from Before HOL Script

### ISSUE THREAD

**Issue by GokhanSenyuz** [microsoft/MCW-Building-the-business-migration-case-with-Windows-Server-and-SQL-Server#9]
Hi,

I am trying to deploy resources for lab from Before HOL script. https://github.com/microsoft/MCW-Building-the-business-migration-case-with-Windows-Server-and-SQL-Server/tree/main/Hands-on%20lab/resources/deployment 

But script deploys 17 resources instead of 22 and it does not deploy SQL MI, only Vnets, VMs, NSG etc. There is no place to enter Azure Ad User ID and Azure ID Login, 

![Lab](https://github.com/microsoft/MCW-Building-the-business-migration-case-with-Windows-Server-and-SQL-Server/assets/37182964/6011c98b-15f1-4cc8-b5c7-81c66437065a)

**Comment by sqllocks** [comment]
Script now deploys 22 resources and has entries for AD Logins.
![wssql](https://github.com/microsoft/MCW-Building-the-business-migration-case-with-Windows-Server-and-SQL-Server/assets/29076762/e5c3acef-a63f-4d57-aad3-4777579047bb)

**Comment by DawnmarieDesJardins** [comment]
Closed the issue as complete with merge of PR #10
